[2023-08-22 15:17:14,354] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: new_etl.insertar_data manual__2023-08-22T15:17:06.494469+00:00 [queued]>
[2023-08-22 15:17:14,366] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: new_etl.insertar_data manual__2023-08-22T15:17:06.494469+00:00 [queued]>
[2023-08-22 15:17:14,368] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 15:17:14,369] {taskinstance.py:1377} INFO - Starting attempt 1 of 4
[2023-08-22 15:17:14,369] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-22 15:17:14,387] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): insertar_data> on 2023-08-22 15:17:06.494469+00:00
[2023-08-22 15:17:14,396] {standard_task_runner.py:52} INFO - Started process 13395 to run task
[2023-08-22 15:17:14,400] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'new_etl', 'insertar_data', 'manual__2023-08-22T15:17:06.494469+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/etl2.py', '--cfg-path', '/tmp/tmpxmolzkem', '--error-file', '/tmp/tmpy8sh1efo']
[2023-08-22 15:17:14,402] {standard_task_runner.py:80} INFO - Job 193: Subtask insertar_data
[2023-08-22 15:17:14,473] {task_command.py:371} INFO - Running <TaskInstance: new_etl.insertar_data manual__2023-08-22T15:17:06.494469+00:00 [running]> on host 0110d0e687e9
[2023-08-22 15:17:14,547] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sol
AIRFLOW_CTX_DAG_ID=new_etl
AIRFLOW_CTX_TASK_ID=insertar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-22T15:17:06.494469+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-22T15:17:06.494469+00:00
[2023-08-22 15:17:25,928] {python.py:173} INFO - Done. Returned value was: None
[2023-08-22 15:17:25,980] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=new_etl, task_id=insertar_data, execution_date=20230822T151706, start_date=20230822T151714, end_date=20230822T151725
[2023-08-22 15:17:26,089] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-22 15:17:26,162] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
